@host = http://localhost:3000
@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NTc0NjAyNzB9.urVcQFz1VIrC2R7ioPVpu8tVw34iztsXX6DFT155mmM


### Users Create Action
POST {{host}}/users
Content-Type: application/json

{
  "username": "testa",
  "email": "testa@test.com",
  "password": "password",
  "password_confirmation": "password"
}

###########################################


### Sessions create (login)
POST {{host}}/sessions.json
Content-Type: application/json

{
  "email": "a@test.com",
  "password": "password"
}

###########################################

### Heros Index Action
GET {{host}}/heroes

### Heros Create Action
POST {{host}}/heroes/new.json
Authorization: Bearer {{jwt}}
Content-Type: application/json 

{
  "name": "test n!!",
  "subname": "test subname",
  "stars": 4,
  "character_id": 1,
  "cover_art_id": 2,
  "game_description": "test gd",
  "first_power_name": "test fpN",
  "first_power_color": "test fpCol",
  "first_power_cost": "test fpCost",
  "first_power_description": "test fpD",
  "first_power_name_alt": "test fpNa",
  "first_power_color_alt": "test fpCola",
  "first_power_cost_alt": "test fpCosta",
  "first_power_description_alt": "test fpDa",
  "second_power_name": "test spN",
  "second_power_color": "test spCol",
  "second_power_cost": "test spCost",
  "second_power_description": "test spD",
  "second_power_name_alt": "test spNa",
  "second_power_color_alt": "test spCola",
  "second_power_cost_alt": "test spCosta",
  "second_power_description_alt": "test spDa",
  "third_power_name": "test tpN",
  "third_power_color": "test tpCol",
  "third_power_cost": "test tpCost",
  "third_power_description": "test tpD",
  "third_power_name_alt": "test tpNa",
  "third_power_color_alt": "test tpCola",
  "third_power_cost_alt": "test tpCosta",
  "third_power_description_alt": "test tpDa",
  "cover_url": "test cu",
  "mpq_art_url": "test mpqa"
}

### Heros Show Action
GET {{host}}/heroes/6.json


### Heros Update Action
PATCH {{host}}/heroes/10.json
Authorization: Bearer {{jwt}}
Content-Type: application/json 

{
  "name": "test n again!"
}

### Heros Destroy Action
DELETE {{host}}/heroes/10
Authorization: Bearer {{jwt}}



###########################################

### MyHeros Index Action
GET {{host}}/my_heroes
Authorization: Bearer {{jwt}}


### MyHeros Create Action
POST {{host}}/my_heroes
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "hero_id": 9
}


### MyHeros Show Action
GET {{host}}/my_heroes/10
Authorization: Bearer {{jwt}}


### MyHeros Update Action
PATCH {{host}}/my_heroes/10
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "first_power_count": 1
}

### MyHeros Destroy Action
DELETE {{host}}/my_heroes/10
Authorization: Bearer {{jwt}}


###########################################


### Comicvine Issues Index
GET http://localhost:3000/comicvine/issues.json

### Comicvine Volumes Index
GET http://localhost:3000/comicvine/volumes.json

### Comicvine Characters Index
GET http://localhost:3000/comicvine/characters.json

### Comicvine Characters By Name
GET http://localhost:3000/comicvine/characters_by_name.json
Content-Type: application/json

{
  "input_name": "Spider-Man"
}

###########################################

### Marvel Character By ID
GET http://localhost:3000/comicvine/character_by_id.json
Content-Type: application/json

{
  "character_id": "1009610"
}

### Marvel Thumbnail By ID
GET http://localhost:3000/comicvine/photo_by_id.json
Content-Type: application/json

{
  "character_id": "1009610"
}
